service: smg-coding-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1
  environment:
    API_ENDPOINT: https://www.thecocktaildb.com/api/json/v1/1/random.php

functions:
  api:
    handler: src/handlers/index.handler
    events:
      - httpApi:
          path: /random-cocktail
          method: get
plugins:
  - serverless-offline